class Exceptions(BaseExceptionGroup):
    class NameTakenError(BaseException): ...
    class UnknownUserError(BaseException): ...
    class BadPasswordError(BaseException): ...
    class InvalidDateError(BaseException): ...